repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.64.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
      args:
        - --args=-no-color
        - --args=-diff
        - --args=-write=false
    - id: terraform_docs
      args:
        - --hook-config=--create-file-if-not-exist=true # you can pass args to hooks !
    - id: checkov
    - id: terrascan
    - id: terraform_tfsec

- repo: local
  hooks:
    - id: terraform-custom-hook
      name: terraform-custom-hook
      entry: python3 python_custom_hook.py
      language: python
      pass_filenames: false

- repo: local
  hooks:
    - id: custom-script-sh
      name: custom-script-sh
      entry: bash_custom_hook.sh
      language: script
      pass_filenames: false